export default {
  '0e384e19': [() => import(/* webpackChunkName: '0e384e19' */ '@site/docs/intro.md'), '@site/docs/intro.md', require.resolveWeak('@site/docs/intro.md')],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '1f391b9e': [() => import(/* webpackChunkName: '1f391b9e' */ '@theme/MDXPage'), '@theme/MDXPage', require.resolveWeak('@theme/MDXPage')],
  '28610e60': [() => import(/* webpackChunkName: '28610e60' */ 'D:\\技术特性测试\\mala-luoye\\luoye-tools\\packages\\document\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json'), 'D:\\技术特性测试\\mala-luoye\\luoye-tools\\packages\\document\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json', require.resolveWeak('D:\\技术特性测试\\mala-luoye\\luoye-tools\\packages\\document\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json')],
  '393be207': [() => import(/* webpackChunkName: '393be207' */ '@site/src/pages/markdown-page.md'), '@site/src/pages/markdown-page.md', require.resolveWeak('@site/src/pages/markdown-page.md')],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ '@generated/docusaurus.config'), '@generated/docusaurus.config', require.resolveWeak('@generated/docusaurus.config')],
  '895ebfd6': [() => import(/* webpackChunkName: '895ebfd6' */ '@site/docs/category2/fun2.md'), '@site/docs/category2/fun2.md', require.resolveWeak('@site/docs/category2/fun2.md')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  'c4f5d8e4': [() => import(/* webpackChunkName: 'c4f5d8e4' */ '@site/src/pages/index.js'), '@site/src/pages/index.js', require.resolveWeak('@site/src/pages/index.js')],
  'd4ef225c': [() => import(/* webpackChunkName: 'd4ef225c' */ 'D:\\技术特性测试\\mala-luoye\\luoye-tools\\packages\\document\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json'), 'D:\\技术特性测试\\mala-luoye\\luoye-tools\\packages\\document\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json', require.resolveWeak('D:\\技术特性测试\\mala-luoye\\luoye-tools\\packages\\document\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json')],
  'e7e2054c': [() => import(/* webpackChunkName: 'e7e2054c' */ '@site/docs/category1/fun1.md'), '@site/docs/category1/fun1.md', require.resolveWeak('@site/docs/category1/fun1.md')],};
